### Settings serial communication node
usb_port: "/dev/STM32_SERIAL" 
publish_odom_tf: false
odom_update_method: "odom"

x_joy_bias: -0.03
y_joy_bias: -0.015
joystick_deadzone: 0.10

#Covariances
#IMU covariance matrices, measured using rosbag during experiment while driving around and calculated using numpy. 0 entry means negligible.

#orientation_cov: [-1, -1, -1,
#                  -1, -1, -1,
#                  -1, -1, -1]

gyro_cov: [0.002, 0, 0,
           0, 0.002, 0,
           0, 0, 0.50]

acc_cov: [0.002, 0, 0,
          0, 0.002, 0,
          0, 0, 0.34]

pose_cov: [0.2, 0, 0, 0, 0, 0,
           0, 0.2, 0, 0, 0, 0,
           0, 0, 0.01, 0, 0, 0,
           0, 0, 0, 0.01, 0, 0,
           0, 0, 0, 0, 0.01, 0,
           0, 0, 0, 0, 0, 0.4]

twist_cov: [0.1, 0, 0, 0, 0, 0,
           0, 0.01, 0, 0, 0, 0,
           0, 0, 0.01, 0, 0, 0,
           0, 0, 0, 0.01, 0, 0,
           0, 0, 0, 0, 0.01, 0,
           0, 0, 0, 0, 0, 0.1]

## calibration parameters odometry
calibration_v_left: 1.00645
calibration_v_right: 0.99365
calibration_cmd_ang: 1.0 #0.42
calibration_cmd_lin: 1.0 #0.7
base_width: 0.51598301091227687

## calibration parameters imu
# bias_acc_x: 0.005
# bias_acc_y: 0.023
#bias_acc_x: -0.008
#unit g
bias_acc_x: 0.0060
bias_acc_y: 0.0045
bias_acc_z: 0 
bias_gyro_x: 0.063
bias_gyro_y: -0.13 
#bias_gyro_z: -0.0007
bias_gyro_z: -0.01
# bias_gyro_z: 0.1
cal_imu_acc: 1.0
cal_imu_gyro: 1.155555


