### Settings serial communication node
usb_port: "/dev/ttyUSB0"
publish_odom_tf: false
apply_vel_filter: true
odom_update_method: "odom"

wheel_acc_limit: 10.0
vel_filter_size: 10

#motor deadzone size, unit is pulse width, if set to 500, motor will run at full speed always
deadzone_pulse_width: 0
#Without person
#motor_kp: 0.35
#motor_ki: 0.028
#motor_kd: 0.0008

#With person
motor_kp: 0.0
motor_ki: 1.5
motor_kd: 0.0
motor_f: 0.0
frequency: 15.0
## calibration parameters odometry
calibration_v_angular: 1.0 #0.88
calibration_v_linear: 1.0 #0.92
calibration_cmd_ang: 1.0 #0.42
calibration_cmd_lin: 1.0 #0.7

## calibration parameters imu
bias_acc_x: 0.035
bias_acc_y: 0.015
bias_acc_z: 0 
bias_gyro_x: 0.0
bias_gyro_y: 0.0 
bias_gyro_z: -0.0025
cal_imu_acc: 1.0
cal_imu_gyro: 1.0


