### Settings serial communication node
usb_port: "/dev/ttyUSB0"
publish_odom_tf: false
apply_vel_filter: true
odom_update_method: "odom"

wheel_acc_limit: 3000.0
vel_filter_size: 10

#Covariances
#IMU covariance matrices, measured using rosbag during experiment while driving around and calculated using numpy. 0 entry means negligible.

#orientation_cov: [-1, -1, -1,
#                  -1, -1, -1,
#                  -1, -1, -1]

gyro_cov: [0.002, 0, 0,
           0, 0.002, 0,
           0, 0, 0.002]

acc_cov: [0.002, 0, 0,
          0, 0.002, 0,
          0, 0, 0.34]

pose_cov: [0.2, 0, 0, 0, 0, 0,
           0, 0.2, 0, 0, 0, 0,
           0, 0, 0.01, 0, 0, 0,
           0, 0, 0, 0.01, 0, 0,
           0, 0, 0, 0, 0.01, 0,
           0, 0, 0, 0, 0, 0.4]

twist_cov: [0.1, 0, 0, 0, 0, 0,
           0, 0.01, 0, 0, 0, 0,
           0, 0, 0.01, 0, 0, 0,
           0, 0, 0, 0.01, 0, 0,
           0, 0, 0, 0, 0.01, 0,
           0, 0, 0, 0, 0, 0.1]

#motor deadzone size, unit is pulse width, if set to 500, motor will run at full speed always
deadzone_pulse_width: 0

#With person
motor_kp: 0.5
motor_ki: 1.3
motor_kd: 0.0
motor_f: 0.0
frequency: 15.0

## calibration parameters odometry
calibration_v_angular: 0.92 #0.88
calibration_v_linear: 0.95 #0.92
calibration_cmd_ang: 1.0 #0.42
calibration_cmd_lin: 1.0 #0.7

## calibration parameters imu
bias_acc_x: 0.035
bias_acc_y: 0.015
bias_acc_z: 0 
bias_gyro_x: 0.0
bias_gyro_y: 0.0 
bias_gyro_z: -0.00325
cal_imu_acc: 1.0
cal_imu_gyro: 1.0


